name: Deploy Development Preview (main branch)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_APP_VERSION: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build (dev)
        run: |
          export DEPLOY_ENV=development
          npm run build

      - name: Deploy to GitHub Pages (dev)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: dev  # this will go to /dev/ under gh-pages
          publish_branch: gh-pages
          keep_files: true

